### ISSUE TITLE
Enhancement: Move display to selected token from DM client

### ISSUE THREAD

**Issue by WiNG-CoMM** [Smashman/table-map-foundryvtt-module#4]
Table Map is great, but there is one quality of life enhancement that would make my life easier as DM. When you load a map, by default, Foundry always centers it on screen. If the map is big enough and the player tokens are located on one of the far sides, you usually just see a black screen on load. Then you have to manually move the cursor in the player table to find where the tokens are. And if you zoom in or out in order to make it easier, you lose the exact sizing on the player screen. It would be great if you could, from the DM screen, select a token and press a key (or menu button) and the player screen focused centered on that token and zoomed to exact 1 inch scale again. Failing that, a key on the player table to zoom back to 1 inch would work good as well after zooming out and moving manually. Thanks a lot

**Comment by Smashman** [comment]
As I typically create my maps to the exact size of the table, I haven't needed to move the map, but I could see the use case for this.

I'm keenly aware that I've not updated Foundry on my local installation in a long time and I've been meaning to put aside some time to update and ensure that TableMap still works. During that time, I'll investigate implementing a zoom only key for the table instance for you.

When initially designing TableMap I investigated sending commands from DM to table user, however I decided it wasn't worth pursuing for my use case. I might look into that again, but no promises.

Cheers

**Comment by Smashman** [comment]
I've implemented a new feature that ought to address this issue.
In [Release 2.1.0](https://github.com/Smashman/table-map-foundryvtt-module/releases/tag/2.1.0) I added the capacity for the GM to use the 'Pan to cursor' keybind. This sends a command via the `socketlib` module which is picked up by the display user's client.
This pans the display screen, but is clamped to ensure it doesn't reveal any padding. So it won't centre the cursor if you're near the edge, but otherwise will.
The new version is on FoundryVTT, so you should be able to simply update TableMap. It will also prompt you to install `socketlib`.
I hope this addressed your request. Drop me a line if you have any questions!

**Comment by WiNG-CoMM** [comment]
Just been finally able to test it (lack of group in the last half of the year until recently) and yeah, it works great. Allowing to pan on my cursor no matter what kind of scale I am using on the DM screen while keeping the scaling on the table works like a charm and it's a better solution to what I initially proposed. I also have a much bigger screen on the table which also helps

**Comment by Smashman** [comment]
Glad to hear it!
